### ISSUE TITLE
LoRa Gateway compile issues

### ISSUE THREAD

**Issue by Vestibule22** [just4give/helium-dyi-hotspot-balena-pi4#4]
I am receiving these errors when sending the balena push command to the Pi. Not sure if this could explain why I am only receiving and not sending anything?
![image](https://user-images.githubusercontent.com/68927795/93955233-20c99600-fd04-11ea-8a4e-983322e3c957.png)

**Comment by shawaj** [comment]
@Vestibule22 can you post the actual code rather than a screenshot if possible?

**Comment by Vestibule22** [comment]
@shawaj This issue is good to close.  Issue was resolved.

**Comment by shawaj** [comment]
@Vestibule22 did you make any changes to the code here or was it just an issue on your side?

**Comment by Vestibule22** [comment]
@shawaj No changes to the code.  I was advised this was happening on everyone's account when they pushed.  Did not have any issue with things running.  There could be a chance that there is still coding changes needed to address this but no issue with the gateway running.
