### ISSUE TITLE
EU868 Plan is incorrect

### ISSUE THREAD

**Issue by ryanteck** [just4give/helium-dyi-hotspot-balena-pi4#5]
The EU868 Plan doesn't look right and looks like US915 to me?

**Comment by just4give** [comment]
I think you are right. I could not test with EU as I am in US. Do you have EU config ? I will update here.

**Comment by shawaj** [comment]
@just4give we have the config files here for various locations https://github.com/PiSupply/iot-lora-gateway/tree/master/template_configs

I'll fix up the 868 one now for your and send a pr

**Comment by ryanteck** [comment]
Just to note we think #10 is correct as they're based on TTN's EU868 plan which we assume is what Helium use. While there's gateways in the UK I couldn't see a clear spec for EU868 on their site.

**Comment by shawaj** [comment]
@ryanteck yep good point. It is yet to be tested
