### ISSUE TITLE
Upload logo for balenaHub inclusion

### ISSUE THREAD

**Issue by shawaj** [just4give/helium-dyi-hotspot-balena-pi4#9]
Can you upload the attached logo to img folder and save it as logo.jpg so we can use for balenaHub?

![20201201_022157](https://user-images.githubusercontent.com/3359418/100690437-6cd92c80-337e-11eb-8324-6ba443bf2249.jpg)

**Comment by just4give** [comment]
Should I create "img" folder at root and copy this image inside?

**Comment by shawaj** [comment]
@just4give it is fine to go in here https://github.com/just4give/helium-dyi-hotspot-balena-pi4/tree/master/web/img

**Comment by just4give** [comment]
Done!
